var array = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10];
var copiedArray = array.slice(3 ,9);
console.log(copiedArray);
var newCopiedArray = copiedArray.splice(1,6);
console.log(newCopiedArray);
var shiftArray = newCopiedArray.shift();
// console.log(shiftArray);
newCopiedArray.unshift(2 , 3);
console.log(newCopiedArray);
newCopiedArray.push(10,11);
console.log(newCopiedArray);
var popArray = newCopiedArray.pop();
console.log(popArray);
var NewArray = newCopiedArray.slice(2,8);
console.log(NewArray);
var spliceArray = NewArray.splice(1,3);
console.log(spliceArray);
var shiftArray1 = spliceArray.shift();
spliceArray.shift();
console.log(shiftArray1);
let lastArray = array.push(2 , 4 ,6 ,8 ,10);
// console.log(lastArray);
console.log(array);
